name: Push Proto to R2

on:
  push:
    branches:
      - main

jobs:
  push-to-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install AWS CLI (v2)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Archive proto files
        run: |
          mkdir dist
          tar -czf dist/protos.tar.gz user/ order/ VERSION

      - name: Upload to R2 (versioned + latest)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}"
          ENDPOINT="https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          BUCKET=${{ secrets.R2_BUCKET_NAME }}

          aws --endpoint-url "$ENDPOINT" s3 cp dist/protos.tar.gz s3://$BUCKET/latest/protos.tar.gz

          # aws --endpoint-url "$ENDPOINT" s3 cp dist/protos.tar.gz s3://$BUCKET/$VERSION/protos.tar.gz

